# Gaussian Operators
The following definition Gaussian operators in terms of their 
Fourier property is made by [@bravyi2005classical].

::: {.definition #gaussianDef name="Gaussian operator"}
An operator $A\in \Cl_{2n}$ with $\tr(A)\neq 0$ is Gaussian if 
\[ 
    X(\theta) = C\exp\left(\df 1 2 \theta^T M\theta + d^T\theta\right)
\] 
for some antisymmetric $(M_{jk})\in \mbb C^{2n\times 2n}$ and 
$d\in \mbb C^{2n}$. We usually mean $d=0$ by default 
when we talk about Gaussian operators, 
and we use ``displaced Gaussian'' to explicitly include the possibility that $d\neq 0$. 
Traceless Gaussian operators are defined as limits. The _correlation matrix _
of $X(\theta)$ as above is in fact $-iM$. 
Two special cases

- Affine Gaussian hermitian operator: in this case the correlation matrix is just $h$ 
\[ 
    H(\theta) = C\exp\left(\df i 2 \theta^T h\theta + d^T\theta\right), 
    \quad (h_{jk})\in \mfk{so}(2n, \mbb R), \quad (d_j)\in \mbb R^{2n}
\] 
- Affine Gaussian unitary: 
\[ 
    U(\theta) = C\exp\left(\df 1 2 \theta^T u\theta + id^T\theta\right), 
    \quad (u_{jk})\in \mfk{so}(2n, \mbb R), \quad (d_j)\in \mbb R^{2n}
\] 
:::
Unlike in traditional statistics, fermionic Gaussians with zero mean 
is the norm rather than exception for most existing research. This is 
partly due to the boson-fermion superselection rule. 
We focus on even Gaussians first then extend known results, as possible, 
to affine Gaussians. 

## Even Gaussian
### Characterization {-}
::: {.theorem #evenGaussianEffect
name="effect of Gaussian unitaries"}
Consider a Gaussian unitary 
\[ 
    U = \exp\left(\df 1 2 \gamma^T h \gamma\right), \quad h_{jk}=-h_{kj}\in \mbb R 
\] 
Then it affects rotation of the majorana operators 
\[ 
    U \gamma_j U^\dag = R_{jk}\gamma_k, \quad R = e^{2h}
\] 
:::
_Proof:_ Using standard Lie theory technique, define $\gamma_j=\theta(0)$ and 
\[ 
    \theta(t) = U(t) \theta(0) U(t)^\dag
    = \tilde \gamma_j(t)\gamma_j, \quad U(t) = \exp\left(\df t 2 \gamma^T h \gamma \right)
\] 
Differentiation yields 
\[ 
    \pd t \theta(t) = 
    \left[\df 1 2 \gamma^T h \gamma, \theta(t) \right]
\] 
The key here is the commutator bracket. 
Using $[\gamma_a\gamma_b, \gamma_a]=-2\gamma_b$ we obtain 
\begin{align}
    \pd t \theta(t) 
    &= \df 1 2 \sum_{a, b, j} \tilde \gamma_j(t)h_{ab}[\gamma_a\gamma_b, \gamma_j]
    = \df 1 2 \sum_{b, j} \tilde \gamma_j(t)h_{jb}[\gamma_j\gamma_b, \gamma_j]
    + \df 1 2 \sum_{a, j} \tilde \gamma_j(t)h_{aj}[\gamma_a\gamma_j, \gamma_j] \\ 
    &= \sum_{j, b} -2 h_{jb} \tilde \gamma_j(t) \gamma_b
    = \sum_b \pd t \tilde \gamma_b(t)\gamma_b  \\ 
    \pd t \tilde \gamma_b(t) &= -2 h_{jb} \gamma_j(t) = 2h_{bj}\gamma_j(t)
\end{align}
The solution to this differential equation is 
\[ 
    \tilde \gamma(t) = R(t)\tilde \gamma(0), \quad R(t) = e^{2h} \in SO(2n)
\] 
It follows that $(UXU^\dag)(\theta) = X(R\theta)$. 

::: {.theorem #unifiedGaussian
name="characterization of Gaussian states"}
The following three characterizations of Gaussian states $\rho$ 
are equivalent. 

- $\rho(\theta) = 2^{-n} \exp(i \theta^T M \theta/2)$. 
- $\rho(\theta) = U(|0\ra \la 0|)^{\otimes n}U^\dag$, for some 
    Gaussian unitary $U$. 
- $\rho = e^{H}/\tr(e^H)$ for some $H$ which is homogeneously quadratic in 
    majorana operators. Pure states are defined in the limit 
    $H\mapsto \lim_{t\to \infty} tH$. 
:::
 

### Fourier perspective {-}
Bravyi's work [@bravyi2004lagrangian] provides many important 
results about Gaussian operators and maps from the Fourier perspective.

::: {.theorem #fourierEvenGaussianCharacterization 
name="fourier characterization of Gaussian operators"}

An operator $X\in \Cl_{2n}$ is Gaussian iff it is even and satisfies 
\[ 
    [\hat \Lambda, X\otimes X]=0, \quad \hat \Lambda = \gamma_a\otimes \gamma_a
\] 
:::

_Proof:_ We first derive the adjoint action of $\hat \Lambda$ in fourier space 
\@ref(lem:adjointLambda). 
The two directions \@ref(lem:fourierEvenGaussianfwd), 
\@ref(lem:fourierEvenGaussianbwd) follow. 

::: {.lemma #adjointLambda}
Consider the following differential operator 
$\Delta_a:\Gr_{2n}\otimes \Gr_{2n}\to \Gr_{2n}\otimes \Gr_{2n}$. 
\[ 
    \Delta_a = 2(\theta_a\otimes \pd a + \pd a \otimes \theta_a)
\] 
For any $Y, Z\in \Cl_{2n}$ having the same parity 
\[  
    [\gamma_a\otimes \gamma_a, Y\otimes Z](\theta) = \Delta_a[Y(\theta)\otimes Z(\theta)]
\] 
:::
_Proof:_ Take $Y, Z$ to be monomials $\gamma_J, \gamma_K$. 
If neither $J, K$ contains $a$ then both sides vanish. 
If both $J, K$ contains $a$, then the LHS vanishes by commutation, 
and both terms of the RHS are annihilated by $\theta_a$. 
If only $J$ contains $a$, then $\gamma_a\otimes \gamma_a$ anticommutes with 
$\gamma_J\otimes \gamma_K$ since $J$ contains one less factor than $K$ for $\gamma_a$ 
to commute across, then 
\[ 
    [\gamma_a\otimes \gamma_a, \gamma_J\otimes \gamma_K] 
    = 2 \gamma_a \gamma_J \otimes \gamma_a \gamma_K 
\] 
On the right hand side, only the second term in $\Delta_a$ survives, with 
\[ 
    2 (\pd a \otimes \theta_a) \theta_J \otimes \theta_K 
\] 
The two coefficients are seen to be equal: commuting $\pd a$ (resp. $\gamma_a$) 
across $\gamma_J$ (resp. $\theta_J$) takes the same number of swaps. 

::: {.lemma #fourierEvenGaussianfwd}

Given a Gaussian operator $X(\theta)=\exp(i\theta^TM\theta/2)$
\[ 
    \sum_a \Delta_a[X(\theta)\otimes X(\theta)]=0\implies [\Lambda, X\otimes X] = 0 
\] 
The traceless case follows by continuity. 
:::

_Proof:_ First compute $\pd a X = i M_{ab}\theta_b X$. This is not at all 
apparant as it seems, the exponential property arises from the power rule 
$\pd x x^n = nx^{n-1}$, which is only true in Grassmann calculus if 
$x$ (in this case $iM_{ab}\theta^TM\theta/2$) is even. Then 
\begin{equation}\begin{aligned}
\left[\hat \Lambda, X\otimes X\right](\theta)
&= 2\sum_a \left(\theta_a \otimes \pd a + \pd a \otimes \theta_a \right)
\exp\left(\df i 2 \theta^T M \theta\right)^{\otimes 2} \\ 
&= 2\sum_{a, b} \theta_a X \otimes iM_{ab} \theta_b X 
    + iM_{ab} \theta_b X \otimes \theta_a X  \\ 
&= 2 i \sum_{a, b} M_{ab} (\theta_a \otimes \theta_b) (X\otimes X) = 0
\end{aligned}\end{equation}

::: {.lemma #fourierEvenGaussianbwd}
Suppose $X\in \Cl_{2n}$ is even with $\sum \Delta_a [X(\theta)\otimes X(\theta)]=0$, 
then $X$ is Gaussian. 
:::

_Proof:_ We provide the proof for non-vanishing trace case. 
Pin down the degree expansion of $X(\theta)$ 
\[ 
    X(\theta) = C + \df{iC}{2} M_{ab}\theta_a\theta_b + O(\theta^4) 
    \iff X(\theta) = C \exp\left(\df{i}{2} M_{ab}\theta_a\theta_b + \cdots\right)
\] 
Apply $1\otimes \pd b$ to the equation of interest, yielding 
\begin{aligned}
    0 &= (1\otimes \pd b) \sum_a (\theta_a X \otimes \pd a X + \pd a X\otimes \theta_a X) \\ 
    &= \sum_a \theta_aX \otimes \pd {ba}^2 X + \pd a X \otimes 
        (\delta_{ab}X - \theta_a \pd b X) \\ 
    &= \pd b X \otimes X + \sum_a \theta_aX \otimes \pd {ba}^2 X 
        - \pd a X \otimes \theta_a \pd b X \\
\end{aligned}
Consider the weaker equation where we only look at the linear term in the second 
tensor component, then the last term above vanishes due to $\theta_a$ 
and the equation simplifies to 
\begin{aligned}
    0 &= \pd b X \otimes C + \sum_a \theta_aX \otimes \df{iC}{2}M_{ab} \implies 
    0 = \pd b X + \df i 2 \sum_a M_{ab} \theta_a X 
\end{aligned}
This suffices to show that $X$ must be Gaussian.


### Gaussian linear maps {-}
::: {.definition #gaussianMapDef name="Gaussian linear map"}
A linear map $\mca E:\Cl_{2n}\to \Cl_{2n}$ is Gaussian if 
\[ 
    \mca E(X)(\theta) = C\int D\eta\, D\mu\, 
    \exp \left[S(\theta, \eta) + i \eta^T \mu\right] X(\mu), \quad 
    S(\theta, \eta) = \df i 2 \begin{pmatrix}
        \theta \\ \eta
    \end{pmatrix} ^T \begin{pmatrix}
        A & B \\ -B^T & D 
    \end{pmatrix} \begin{pmatrix}
        \theta \\ \eta
    \end{pmatrix}
    (\#eq:gaussianLinearMap)
\] 
Here $A, D$ are antisymmetric and $B$ arbitrary. All values are complex. 
It's also insightful to expand the whole expression using 
$\theta^TB\eta - \eta^TB^T\theta = 2\theta^T B \eta$ 
\[ 
    \mca E(X)(\theta) = C\exp\left(\df i 2 
        \theta^TA\theta\right)\int D\eta\, 
    \exp \left[(iB^T \theta)^T \eta + \df i 2 \eta^T D \eta
    \right] \int D\mu\, \exp(i \eta^T \mu) X(\mu)
    (\#eq:gaussianLinearMapExtended)
\] 
:::

::: {.example #identityExample name="identity map"}
Recalling the Grassmann dirac delta \@ref(def:diracDelta). 
\[ 
    X(\theta) = \int D\eta\, D\mu\, \exp(i\theta^T\eta + i\eta^T\mu) X(\mu) 
    \implies S = \begin{pmatrix}
        0 & I \\ -I & 0
    \end{pmatrix}
\] 
:::

::: {.proposition}
Gaussian linear maps are parity-preserving. 
:::
_Proof:_ Consider the automorphism $\overline{(\cdot)}$ 
such that $\overline X(\theta) = X(-\theta)$. It suffices to prove that 
\[ 
    \overline{\mca E(X)} = \mca E(\overline X)
\] 
Here $\overline{\mca E(X)}(\theta)$ is equivalent to replacing 
$\theta\mapsto -\theta$ in \@ref(eq:gaussianLinearMap), while 
$\mca E(\overline X)(\theta)$ 
is equivalent to replacing $\mu\mapsto -\mu$. 
They yield the same expression upon substitution by virtue of 
$S(\theta, -\eta) = S(-\theta, \eta)$ 
and $D(-\mu) = D\mu, D(-\eta) = D\eta$. 


::: {.proposition}
Gaussian linear maps map Gaussian operators into Gausian operators. 
:::
_Proof:_ Since $\mca E$ is parity preserving, it suffices to apply 
\@ref(thm:fourierEvenGaussianCharacterization) on $\mca E(X)$, for $X$ Gaussian. 
Note the following identity 
\begin{equation}
    \sum_a (\theta_a\otimes \pd {\theta_a} + \pd {\theta_a}\otimes \theta_a) 
        (e^{i\theta^TB\eta})^{\otimes 2}
    = -\sum_a (\eta_a\otimes \pd {\eta_a} + \pd {\eta_a}\otimes \eta_a) 
        (e^{i\theta^TB\eta})^{\otimes 2}
    (\#eq:convenientIdentity)
\end{equation}
We also need the Leibniz rule \@ref(prp:leibniz) and integration 
by part formula \@ref(prp:integrationByPart). Rewrite \@ref(eq:gaussianLinearMap) 
using an auxillary polynomial $f(\eta)$ 
\[ 
    \mca E(X)(\theta) = C\int D\eta\, 
    \exp \left[S(\theta, \eta)\right] f(\eta), \quad 
    f(\eta) = \int D\mu\, e^{i\eta^T\mu} X(\mu)
\] 
One can show that $f(\eta)$ is even. One can go on to show that 
\[ 
    \Lambda_{\mrm{ad}} \, \mca E(X)\otimes \mca E(X) 
    = \mca E\otimes \mca E(\Lambda_{\mrm{ad}}\, X\otimes X) = 0
\] 

::: {.theorem name="effect of Gaussian linear maps"}
Let $X$ be a Gaussian operator with correlation $M$ and pre-exponential 
factor $C$, then $\mca E(X)$ as defined in \@ref(eq:gaussianLinearMap) 
has correlation matrix 
\begin{equation} 
    \mca E(M) = B(M^{-1}+D)^{-1}B^T + A 
(\#eq:linearMapCovGeneral)
\end{equation}
The pre-exponential factor is 
\begin{equation} 
\begin{split}
    \tr\, \mca E(X) &= C (-1)^n \Pf(M)\Pf(M^{-1}+D)\tr(X) \\ 
    \tr[\mca E(X)]^2 &= C^2 \det (I+MD)\tr(X)^2
\end{split}
(\#eq:linearMapTrace)
\end{equation} 
:::

_Proof:_ Picking up from \@ref(eq:gaussianLinearMapExtended)
\begin{align}
    \mca E(X)(\theta) 
    &= C\, \tr(X)\, \exp\left(\df i 2 
        \theta^TA\theta\right)\int D\eta\, 
    \exp \left[(iB^T \theta)^T \eta + \df i 2 \eta^T D \eta
    \right] \int D\mu\, \exp(i \eta^T \mu + \df i 2 \mu^T M \mu) X(\mu) \\ 
    &= i^n C \, \Pf(M)\, \tr(X) \exp \left(\df i 2 
        \theta^TA\theta \right) \int D\eta\, 
    \exp \left[ (iB^T\theta)^T \eta + \df i 2 \eta^T (D+M^{-1}) \eta\right] \\ 
    &= i^n C \, \Pf(M)\, \tr(X) \exp \left(\df i 2 
        \theta^TA\theta \right) i^n \Pf(D+M^{-1}) 
    \exp\left[\df i 2 \theta^T B (D+M^{-1})^{-1} B^T \theta\right] \\ 
    &= (-1)^n C \, \Pf(M)\, \Pf(D+M^{-1}) \, \tr(X)
    \exp\left[\df i 2 \theta^T (B (D+M^{-1})^{-1} B^T + A)\theta\right]
\end{align}
The $\tr[\mca E(X)]^2$ formula follows from $\Pf(A)^2=\det A$ and 
$\det A\, \det B = \det(AB)$. 

::: {.corollary name="trace-preserving bistochastic linear maps"}
If $\mca E$ is trace-preserving (TP), then $D=0$ and $C=1$ in 
\@ref(eq:gaussianLinearMap), in which case 
\[ 
    \mca E(M) = BMB^T + A 
\] 
If $\mca E$ is bistochastic (i.e. preserves the identity) 
then $A=D=0$ and 
\[ 
    \mca E(M) = BMB^T 
\] 
:::

### Complete-positive Gaussian linear maps {-}
It turns out that, when interpreted as a Gaussian channel, the $4n\times 4n$ 
block matrix in \@ref(eq:gaussianLinearMap) is the covariance matrix 
of the corresponding Choi state. 

::: {.theorem name="fourier characterization of CP Gaussian linear maps"}
$\mca E$ is completely positive if $C\geq 0$ and 
\[ 
    E = \begin{pmatrix} 
        A & B \\ -B^T & D 
    \end{pmatrix}
\] 
satisfies $E^TE \leq I$. 
:::
To prove this, we need a notion of fermionic tensor product of linear maps. 

::: {.definition name="fermionic tensor product map"}
Given $\mca E_1, \mca E_2:\Cl_{2n}\to \Cl_{2n}$, define 
$\mca E_1\otimes_f \mca E_2:\Cl_{4n}\to \Cl_{4n}$ by 
\[ 
    (\mca E_1\otimes_f\mca E_2)(\gamma_J\gamma_K) = \mca E_1(\gamma_J)\mca E_2(\gamma_K)
\] 
where $\gamma_J$ is supported on the first $n$ modes and $\gamma_K$ is supported on the last $n$ modes. 
:::

::: {.lemma}
Given a parity preserving linear map $\mca E$, $\mca E\otimes 1$ is positive if and only 
if $\mca E\otimes_f 1$ is positive. 
:::
_Proof:_ Let $\iota:\Cl_{2n}\otimes \Cl_{2n}\to \Cl_{4n}$ be the natural unitary 
isomorphism which converts between the natural (commuting) and fermionic (anti-commuting) tensor 
products of majorana operators. 
\[
    \iota(\gamma_J\otimes \gamma_K) = \gamma_J \hat P_2^{j} \gamma_{2n+K}
\] 
With a slight overload of notation above, the $\gamma$ on the RHS are elements of $\Cl_{4n}$ while those 
on the LHS are elements of $\Cl_{2n}$, and $2n+K$ denotes the multi-index with each element shifted by $2n$. 
Here $\hat P_2$ is the parity operator of $1\otimes \mca Cl_{2n}\subset \Cl_{4n}$, in the JW representation 
simply $I^{\otimes n}\otimes Z^{\otimes n}$. Then by parity preserving, the parity of $\mca E(\gamma_J)$ 
is the same as that of $\gamma_J$, so 
\begin{align}
    [\iota^{-1}\circ (\mca E\otimes_f 1)\circ \iota] (\gamma_J\otimes \gamma_K)
    = [\iota^{-1}\circ (\mca E\otimes_f 1)] (\gamma_J \hat P_1^j \gamma_{2n+K})
    = \iota^{-1}(\mca E(\gamma_J) \hat P_1^j \gamma_{2n+K}) = \mca E(\gamma_J)\otimes \gamma_K
\end{align}
Now $\iota$ 

## Lie algebra embedding
Results from [@knill2001fermionic] provide the mathematical 
link between even and affine Gaussians. 

::: {.definition #gaussianLie name="Gaussian Lie groups and algebras"}
Fixing $n$ fermionic modes

- Let $\mca L_1, \mca L_2$ denote the linear and quadratic polynomials in $2n$ 
    majorana operators, respectively. 
- Let $\mca L_2'$ denote quadratic monomials. 
    Note that $\dim \mca L_2=2n^2 + n + 1, \dim \mca L_2'=2n^2-n$. 
- Let $\mca L_2^*$ denote the quadratic polynomials without constant terms, so 
    $\dim \mca L_2^*=2n^2+n$. 
:::

::: {.theorem #evenReduction name="even Gaussian algebra reduction"}
the affine Gaussian algebra $\mca L_2^*$ is isomorphic to a subalgebra 
of the even Gaussian algebra $\mca L_2'$ on one more mode.
:::

_Proof:_ Let the new mode append majorana operators $\gamma_{2n+1}, \gamma_{2n+2}$. 
Consider $\iota:\mca L_2^*\to \mca L_2'$ acting on generators and extending multiplicatively 
\[ 
    \iota(\gamma_j) = -i \gamma_j \gamma_{2n+1}\implies 
    \iota(\gamma_j\gamma_k) = \iota(\gamma_j)\iota(\gamma_k) = \gamma_j\gamma_k
\] 
It appends $-i\gamma_{2n+1}$ to linear terms and 
leaves quadratic terms unchanged. This is manifestly and injection, to 
demonstrate embedding it then suffices to show that 
$\iota\, [a, b] = [\iota\, a, \iota\, b]$. Consider the following representative 
cases with nonvanishing brackets
\begin{aligned}
    \iota\, [\gamma_1, \gamma_2] &= \iota(2\gamma_1\gamma_2) = 2\gamma_1\gamma_2 \\ 
    [\iota\, \gamma_1, \iota\, \gamma_2] 
    &= [i\gamma_1\gamma_{2n+1}, i\gamma_2\gamma_{2n+1}] = 2\gamma_1\gamma_2 \\ 
    \iota[\gamma_1, \gamma_1\gamma_2] 
    &= \iota(2\gamma_2) = 2i\gamma_2\gamma_{2n+1} \\ 
    [\iota\, \gamma_1, \iota\, \gamma_1\gamma_2] 
    &= [i\gamma_1\gamma_{2n+1}, \gamma_1\gamma_2] = 2i\gamma_2\gamma_{2n+1}
\end{aligned}
This underpins the construction in lemma \@ref(lem:dgEmbedding). 

## Displaced Gaussian

::: {.proposition name="displaced Gaussian unitary action"}
Consider a displaced Gaussian unitary and a quadratic operator 
\begin{equation} 
    U = \exp\left(\df 1 2 \gamma^T h \gamma + id^T \gamma\right), \quad 
    A = \df 1 2 \sum_{a, b}\Gamma_{ab}\gamma_a \gamma_b + \sum_j \Gamma_j \gamma_j, 
    \quad \Gamma_{ab}=-\Gamma_{ba}
    (\#eq:dispGaussianUnitary)
\end{equation}
Define the affine encodings $\psi, \iota$ of the coefficients 
\begin{equation}
\begin{split}
    E &= \psi(U) = \begin{pmatrix}
        0 & \cdots & -id_k & \cdots \\ 
        \vdots & \ddots && \\ 
        -id_j && h_{jk} & \\ 
        \vdots  &&& \ddots 
    \end{pmatrix}, \quad 
    \iota\left(A\right) = 
    \begin{pmatrix}
        0 & \cdots & -\Gamma_k & \cdots \\ 
        \vdots & \ddots && \\ 
        \Gamma_j & & \Gamma_{jk} & \\ 
        \vdots &&& \ddots \\ 
    \end{pmatrix}
\end{split}
(\#eq:affEncoding)
\end{equation}
Note that the encoding $\psi$ of unitary is anti-Hermitian 
while the encoding $\iota$ of $A$ is antisymmetric. 
The displaced Gaussian unitary effects \@ref(eq:dispGaussianUnitary)
\[ 
    \iota(UAU^\dag) = V\, \iota(A) \, V^T, \quad V = \exp(2E)
\] 
Denote the Gaussian unitary group by $DG(n)\subset U(2^n)$ and 
its algebra $\mfk{dg}(n)$. 
:::

::: {.lemma #dgEmbedding}
The DG algebra $\mfk{dg}(n)$ is isomorphic to $\mfk{so}(2n+1)$. 
As a corollary, $DG(n)$ is isomorphic to $SO(2n+1)$. 
:::
_Proof:_ Define the embedding $\varphi:\mfk{dg}(n)\to \mfk{so}(2n+1)$ by 
\[ 
    \varphi \begin{pmatrix} 0 & -id^T \\ -id & h 
    \end{pmatrix} = \begin{pmatrix}
        0 & d^T \\ -d & h
    \end{pmatrix}
\] 
The map $\varphi$ is obviously bijective. Showing 
$[\varphi(E_1), \varphi(E_2)] = \varphi[E_1, E_2]$ establishes 
that this is a bijection
\begin{align}
    [\varphi(E_1), \varphi(E_2)] &= \left[\begin{pmatrix}
        0 & d_1^T \\ -d_1 & h_1
    \end{pmatrix}, \begin{pmatrix}
        0 & d_2^T \\ -d_2 & h_2
    \end{pmatrix}\right] = \begin{pmatrix}
        - d_1^T d_2 + d_2^Td_1 & d_1^T h_2 - d_2^T h_1 \\ 
        -h_1 d_2 + h_2 d_1 & h_1h_2 - d_1d_2^T - h_2h_1+ d_2d_1^T 
    \end{pmatrix} \\ 
    &= \begin{pmatrix}
        0 & -(h_2d_1 - h_1d_2)^T \\ 
        h_2d_1 - h_1d_2 & [h_1, h_2] + d_2d_1^T - d_1d_2^T
    \end{pmatrix} \\ 
    \varphi [E_1, E_2] 
    &= \varphi \left[
        \begin{pmatrix} 0 & -id_1^T \\ -id_1 & h_1\end{pmatrix}
        ,
        \begin{pmatrix} 0 & -id_2^T \\ -id_2 & h_2\end{pmatrix}
    \right] 
    = \varphi \begin{pmatrix}
        -id_1^T d_2 + id_2^T d_1 & -id_1^T h_2 + id_2^Th_1 \\ 
        -ih_1d_2 + ih_2d_1 & h_1h_2 -d_1d_2^T - h_2h_1 + d_2 d_1^T
    \end{pmatrix} \\ 
    &= \varphi \begin{pmatrix}
        0 & -i (d_1^Th_2 - d_2^Th_1)\\ 
        i(h_2d_1 - h_1d_2) & [h_1, h_2] + d_2d_1^T - d_1d_2^T
    \end{pmatrix} = \begin{pmatrix}
        0 & -(h_2d_1 - h_1d_2)^T \\ 
        h_2d_1 - h_1d_2 & [h_1, h_2] + d_2d_1^T - d_1d_2^T
    \end{pmatrix}
\end{align}

::: {.theorem #dispGsDecomp name="local decomposition of displaced Gaussian"}
Displaced Gaussian unitaries are generated by nearest-neighbor even Gaussian 
and arbitrary single-qubit unitary on a special line. 
:::
_Proof:_ Let the first line be special without loss of generality. 
As per the previous lemma \@ref(lem:dgEmbedding) it suffices to show that 
the rotations generated by the image of matchgates and $R_x$ under $\varphi$ 
generate $SO(2n+1)$. 
The image of matchgates under $\varphi$. generate rotations on all subspaces but the first. 

Now $R_x(\theta)$ first line correspond to zero $h$ and 
nonzero $d_j=-\delta_{1j}\theta/2$. Explicilty, 
\begin{align}
    \varphi\circ\psi(e^{-i \theta \gamma_1/2}) 
    &= \varphi \begin{pmatrix}
        0 & i\theta/2 & \cdots \\ 
        i\theta/2 \\ 
        \vdots && \ddots \\ 
    \end{pmatrix} = \begin{pmatrix}
        0 & -\theta/2 \\ 
        \theta/2 & 0 \\ 
        &&& \ddots 
    \end{pmatrix} 
\end{align}
Thus $R_x(\theta)$ generates rotation between the first and second subspaces. 
This suffices to generate $SO(2n+1)$ together with arbitrary rotation in all subspaces but the first. 


::: {.proposition name="decomposition of GHZ state"}
Let $|GHZ_4\ra = |0000\ra + |1111\ra$ denote the $4$-qubit GHZ state. Consider the unitaries 
\begin{align}
    U_1 &= \exp\left[\df \pi 4 (3\gamma_1\gamma_7 + \gamma_3\gamma_5 - 4\gamma_4\gamma_8)\right] \\ 
    U_2 &= \exp\left[\df \pi 4 (3\gamma_2\gamma_8 + 4\gamma_5\gamma_6)\right]
\end{align}
Let $CZ_{12}$ denote controlled-$Z$ on the first and second qubits, then 
\[ 
    |GHZ_4\ra = U_2CZ_{12}U_1|0\ra^{\otimes 4}
\] 
:::